server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: coupon-management-api
  datasource:
    url: jdbc:mysql://localhost:3306/coupondb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Rahul@123
  jpa:
    hibernate:
      ddl-auto: update           # change from create-drop to update for MySQL
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    com.monkcommerce.coupon: DEBUG
    org.hibernate.SQL: DEBUG

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
